#!/bin/sh

git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --relative .
if [ $? -ne 0 ]; then 
    echo 'Something is not OK.'
    exit 1; 
else
    echo 'everything is OK'    
fi