name: CI_Go

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
          
      - name: Install dependencies
        run: |
            go version

      - name: Run build
#         run: /home/go/myapp/go build
        run: |
           mkdir -p /home/runner/go/src/
           mv myapp /home/runner/go/src/
           cd /home/runner/go/src/myapp && go mod download
           go build /home/runner/go/src/my_app/main.go
