name: CI_Go

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
          
      - name: Install dependencies
        run: |
            go version

      - name: Run build
        run: go build
